### ASSIGNMENT No: 09 

Title: Write a python program to design a Hopfield Network which stores 4 vectors  

Problem Statement:  Design a Hopfield Network which stores 4 vectors 

In [ ]:
# !pip install numpy

# (Latest version upgrade)
# !pip install -U numpy

In [6]:
import numpy as np

In [7]:
patterns = np.array([
    [1, -1, 1, -1],
    [-1, 1, -1, 1],
    [1, 1, -1, -1],
    [-1, -1, 1, 1]
])

In [8]:
class HopfieldNetwork:
    
    def __init__(self):
        self.W = None   # weight matrix

    # 🔹 Train using Hebbian Learning
    def train(self, patterns):
        n = patterns.shape[1]
        self.W = np.zeros((n, n))
        
        for p in patterns:
            p = p.reshape(n, 1)
            self.W += p @ p.T   # outer product
        
        # remove self connections
        np.fill_diagonal(self.W, 0)

    # 🔹 Recall function
    def recall(self, x, steps=5):
        x = x.copy()
        
        for _ in range(steps):
            for i in range(len(x)):
                x[i] = np.sign(np.dot(self.W[i], x))
        
        return x

In [9]:
model = HopfieldNetwork()
model.train(patterns)

print("Weight Matrix:\n", model.W)

Weight Matrix:
 [[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]


In [10]:
# slightly corrupted pattern
test = np.array([1, -1, -1, -1])

print("Input:", test)
print("\n")

output = model.recall(test)

print("Recovered Output:", output)

Input: [ 1 -1 -1 -1]


Recovered Output: [ 1  1 -1 -1]
